name: Unzip and Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2
     with: 
node-version: '20'

    - name: Install Git LFS
      run: |
        echo "Installing Git LFS..."
        sudo apt-get update
        sudo apt-get install git-lfs
        git lfs install

    - name: Download zip file
      run: |
        echo "Starting download..."
        wget http://audio1.wordfree.net/bibles/app/audio/7_1.zip -O 1.zip
        if [ $? -eq 0 ]; then
          echo "Download completed successfully."
        else
          echo "Download failed."
          exit 1
        fi

    - name: Verify download
      run: |
        if [ -f "1.zip" ]; then
          echo "File downloaded successfully."
        else
          echo "File download failed."
          exit 1
        fi

    - name: Unzip file
      run: |
        echo "Unzipping file..."
        unzip 1.zip -d Fr_Lous
        if [ $? -eq 0 ]; then
          echo "Unzipping completed successfully."
        else
          echo "Unzipping failed."
          exit 1
        fi

    - name: List contents of Fr_Lous folder
      run: |
        echo "Contents of Fr_Lous folder:"
        ls -l Fr_Lous

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Track large files with Git LFS
      run: |
        echo "Tracking large files with Git LFS..."
        cd Fr_Lous
        git lfs track "*"
        cd ..

    - name: Add changes to git
      run: |
        git add Fr_Lous
        if [ $? -eq 0 ]; then
          echo "Files added to git successfully."
        else
          echo "Failed to add files to git."
          exit 1
        fi

    - name: Commit changes
      run: |
        git commit -m 'Add unzipped files to Fr_Lous folder'
        if [ $? -eq 0 ]; then
          echo "Commit successful."
        else
          echo "Commit failed."
          exit 1
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GIT_FORCE: true
